/**
 * Shared TypeScript types for the ShopStream API.
 */

/** Represents a single active live stream */
export interface StreamInfo {
  /** The unique stream key used in the RTMP push URL */
  streamKey: string;
  /** ISO 8601 timestamp of when the stream started */
  startedAt: string;
  /** IP address of the publishing client */
  clientIp: string;
  /** Available quality renditions generated by FFmpeg */
  qualities: QualityLevel[];
  /** Master ABR playlist URL (HLS) */
  masterPlaylistUrl: string;
}

/** A single ABR quality rendition */
export interface QualityLevel {
  label: string;        // e.g. "1080p"
  bitrate: number;      // in kbps
  resolution: string;   // e.g. "1920x1080"
  playlistUrl: string;  // URL to the specific quality playlist
}

/** MediaMTX webhook payload (on-publish / on-unpublish) */
export interface MediaMTXWebhookPayload {
  /** The path/stream key published (e.g. "live/mystream" or "mystream") */
  name: string;
  /** Source IP that is publishing the stream */
  remoteAddr?: string;
  /** Protocol used (rtmp, srt, webrtc, etc.) */
  proto?: string;
}

/** API response wrapper */
export interface ApiResponse<T> {
  success: boolean;
  data: T;
  timestamp: string;
}
